### ISSUE TITLE
Search issues on mobile

### ISSUE THREAD

**Issue by 3incognito** [zaphosting/docs#1331] opened 2024-10-05 20:25 UTC
When you search for something on your phone, you cannot see what you are typing. If there is no result, it appears as if the input has been written backwards, which is actually the case. Also, you cannot delete what you have typed.

This happens on Google Chrome, i haven't tested it on a different browser.

![Screenshot_20241005-222222~2.png](https://github.com/user-attachments/assets/a387a466-fdec-4992-8103-1795e5deec6c)

**Comment by Blumlaut** [comment] 2024-10-05 20:58
fixed in #1332

**Comment by Blumlaut** [comment] 2024-10-05 21:20
search bar width is fixed, however, LTR text issue still persists, i noticed there is a `direction: ltr` style property set but im not sure why that would cause RTL text to be typed.

**Comment by Blumlaut** [comment] 2024-10-11 09:19
cannot reproduce anymore on chrome 129.0.6668.100

**Closed by Blumlaut** 2024-10-11 09:19 UTC
